### ISSUE TITLE
Training on sketchy TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Anurag14** [sounakdey/doodle2search#6]
Respected Authors,
I am unable to run the code for the sketchy dataset. It mentioned class labels file is missing so i created a labels file for the dataset. I am unable to comprehend the error in the code. It would be really nice if you can let me know what can I do to reproduce the results.
```
python3 src/train.py sketchy_extend --data_path /data/anurag/doodledata/sketchy
Parameters:	Namespace(attn=False, batch_size=20, data_path='/data/anurag/doodledata/sketchy', dataset='sketchy_extend', decay=0.0005, early_stop=20, emb_size=256, epochs=1000, exp_idf=None, gamma=0.1, grl_lambda=0.5, learning_rate=0.0001, load=None, log=None, log_interval=20, momentum=0.9, ngpu=1, nopretrain=True, plot=False, prefetch=2, save=None, schedule=[], seed=42, w_domain=1, w_semantic=1, w_triplet=1)
Prepare data
Traceback (most recent call last):
  File "src/train.py", line 287, in <module>
    main()
  File "src/train.py", line 99, in main
    train_data, [valid_sk_data, valid_im_data], [test_sk_data, test_im_data], dict_class = load_data(args, transform)    
  File "/data/anurag/codes/baselines/doodle2search/src/data/generator_train.py", line 18, in load_data
    return Sketchy_Extended(args, transform)
  File "/data/anurag/codes/baselines/doodle2search/src/data/sketchy_extended.py", line 35, in Sketchy_Extended
    class_emb = create_class_embeddings(list_class, args.dataset)
  File "/data/anurag/codes/baselines/doodle2search/src/data/class_word2vec.py", line 9, in create_class_embeddings
    model = Word2Vec(google_300_corpus)
  File "/home/anurag/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 783, in __init__
    fast_version=FAST_VERSION)
  File "/home/anurag/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 759, in __init__
    self.build_vocab(sentences=sentences, corpus_file=corpus_file, trim_rule=trim_rule)
  File "/home/anurag/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 936, in build_vocab
    sentences=sentences, corpus_file=corpus_file, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/anurag/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1592, in scan_vocab
    total_words, corpus_count = self._scan_vocab(sentences, progress_per, trim_rule)
  File "/home/anurag/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1561, in _scan_vocab
    for sentence_no, sentence in enumerate(sentences):
  File "/home/anurag/anaconda3/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 355, in __getitem__
    return vstack([self.get_vector(entity) for entity in entities])
TypeError: 'int' object is not iterable
```

**Comment by bennyguo** [comment]
Same problem

**Comment by MericCelik** [comment]
Same here

**Comment by umdreamer** [comment]
In file data/class_word2vec.py, on the line 8 and 9.
```
google_300_corpus = api.load("word2vec-google-news-300")
model = Word2Vec(google_300_corpus)
```
change to 
```
google_300_corpus = api.load("word2vec-google-news-300")
model = google_300_corpus
```
As the **word2vec-google-news-300** is a model, not a corpus. There is no need to do another word2vec operation.

Hope this helps.

**Comment by buptlmk** [comment]
Hello，Can you reproduce the result？
